# Site settings
title: 行而学之
header-img: "img/16.jpg"
tagline: "cn"  
description: "罗学焕|生而行·行而学"  
baseurl: ""
url: "http://www.luoxuehuan.com"  

# About/contact
owner: 
  name: " luoxuehuan"
  email: lxuehuan@gmail.com
  bio: "行就是最好的学习"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/icon1.jpg

# 1douban_username:luoxuehuan1
twitter_username: luoxuehuan
github_username: luoxuehuan
facebook_username: luoxuehuan
weibo_username: luoxuehuan
zhihu_username: luoxuehuan

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "luoxuehuan"
      header-img: "img/16.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : 
  disqus :
      short_name : 

# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
